runtime: python311  # Use the appropriate Python version

entrypoint: gunicorn -b :$PORT wsgi:application  # Updated entrypoint for Gunicorn with wsgi.py

env_variables:
  FLASK_ENV: "production"
  FLASK_APP: "app.py"

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
